server:
  port: 9000

spring:  h2:    console:      enabled: true
      
#  datasource:#    dbcp2:#      driver-class-name: org.h2.Driver
#      url: jdbc:h2:mem:testdb
#      username: sa
#      password: 
#
#  jpa:#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:#      ddl-auto: create-drop

  datasource:    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@DESKTOP-2L5NM4J:1521/XE
    username: hr
    password: hr
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop